git:
  auto_commit: false
  auto_stage: false
logging:
  level: INFO
model:
  parameters:
    frequency_penalty: 0.0
    max_tokens: 2000
    presence_penalty: 0.0
    temperature: 0.2
    top_p: 0.95
  platform: togetherai
  together_api_key: YOUR_API_KEY_HERE
